title: Windows to Glory
author: Me
email: windows2glory@
description: > # this means to ignore newlines until "baseurl:"
  This is a personal story of my journey of faith, a place for my
  thoughts, and why I believe what I believe.

# social links
twitter_username: your-twitter-handle
github_username:  windows2glory

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
